spring:
  application:
    name: QrCloud
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  datasource:
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/qr_cloud
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
